"""Added Relationships between articles and userss models

Revision ID: 275e8c8b2d9e
Revises: ffa2defe7712
Create Date: 2025-06-10 11:52:27.779613

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "275e8c8b2d9e"
down_revision: Union[str, None] = "ffa2defe7712"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(
        "articles_user_id_fkey",
        "articles",
        "users",
        ["user_id"],
        ["id"],
        # source_schema='dev',
        # referent_schema='dev'
    )
    op.drop_column(table_name="articles", column_name="author")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("author", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        constraint_name="articles_user_id_fkey",
        table_name="articles",
        type_="foreignkey",
    )
    op.drop_column(table_name="articles", column_name="user_id")
    # ### end Alembic commands ###
