"""Added secret_info and release_date fields to ArticleSchema

Revision ID: ffa2defe7712
Revises: 89ab6c87e681
Create Date: 2025-06-02 16:32:33.006454

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ffa2defe7712"
down_revision: Union[str, None] = "89ab6c87e681"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "articles",
        sa.Column("release_date", sa.DateTime(), nullable=False),
        schema="dev",
    )
    op.add_column(
        "articles", sa.Column("secret_info", sa.String(), nullable=True), schema="dev"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "secret_info", schema="dev")
    op.drop_column("articles", "release_date", schema="dev")
    # ### end Alembic commands ###
